-- AlterTable
ALTER TABLE "TSLMessage" ADD COLUMN "BRIGHTNESS" INTEGER;
ALTER TABLE "TSLMessage" ADD COLUMN "IS_CONTROL_DATA" BOOLEAN;
ALTER TABLE "TSLMessage" ADD COLUMN "LH_TALLY" INTEGER;
ALTER TABLE "TSLMessage" ADD COLUMN "RH_TALLY" INTEGER;
ALTER TABLE "TSLMessage" ADD COLUMN "TEXT_TALLY" INTEGER;
